version: "3.3"
services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: importTest
      VIRTUAL_HOST: mysql.dev.loc
    ports:
      - "3306:3306"
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
  php-fpm:
    image: php:7.4-cli
    hostname: php-fpm
    volumes:
      - "./:/app"
    working_dir: "/app"
    depends_on:
      - mysql
  nginx:
    image: webdevops/nginx
    hostname: nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
    ports:
      - "80:80"
    volumes:
      - "./:/app"
    depends_on:
      - php-fpm
