version: "3.3"
services:
  php-fpm:
    depends_on:
      - mysql
    image: webdevops/php-dev:7.4
    hostname: php-fpm
    volumes:
      - "./:/app"
    working_dir: "/app"
  mysql:
    image: mysql:5.7
    container_name: dbms-container
    env_file:
      - ./.env.local
    hostname: mysql
    environment:
      VIRTUAL_HOST: mysql.dev.loc
    ports:
      - "3306:3306"
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
  nginx:
    image: webdevops/nginx
    depends_on:
      - mysql
      - php-fpm
    hostname: nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
    ports:
      - "80:80"
    volumes:
      - "./:/app"
